#!/usr/bin/env bash
#Install nginx
sudo apt-get -y update && sudo apt-get -y install nginx && sudo chown -R ubuntu:ubuntu /var/www && sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html && sudo service nginx start
