#!/usr/bin/env bash
#Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80/tcp
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
