#!/usr/bin/env bash
# Install your load balancer
sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update
sudo apt install -y haproxy=2.0.\*
echo -e "listen 1445-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\tserver 1445-web-01 35.185.117.46 check\n\tserver 1445-web-02 34.75.3.166:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
 
