#!/usr/bin/env bash
# Install your load balancer
sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update
sudo apt install -y haproxy=2.0.\*
echo -e "listen 1125-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\tserver 1125-web-01 35.227.27.183 check\n\tserver 1125-web-02 34.74.72.60:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart 
