#!/usr/bin/env bash
#Accepts a string as an argument and display and Ping the IP 5 times
if [ $# -lt "1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
