#!/usr/bin/env bash
# 4 bad luck, 8 is your chance 
a=0
while 
[ $a -le 9 ];
do
if 
[ $a -eq 3 ];
then
echo bad luck
elif 
[ $a -eq 7 ];
then
echo good luck
else
echo Holberton School
fi
((a++))
done 
