#!/usr/bin/env bash
# 4 bad luck, 8 is your chance 
a=1
while 
[ $a -le 20 ];
do
echo $a
case $a in
4)
echo bad luck from China
;;
9)
echo bad luck from Japan
;;
17)
echo bad luck from Italy
;;
esac
((a++))
done
